"""add monthly period tracking to contributions and users

Revision ID: 2f6cc2988d10
Revises: b496014c8b97
Create Date: 2026-08-19 21:35:39.193858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f6cc2988d10'
down_revision: Union[str, Sequence[str], None] = 'b496014c8b97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('contributions', sa.Column('period', sa.String(length=7), nullable=True))
    op.execute(
        "UPDATE contributions SET period = "
        "to_char(created_at AT TIME ZONE 'Asia/Karachi', 'YYYY-MM')"
    )
    op.alter_column('contributions', 'period', nullable=False)
    op.create_unique_constraint('uq_user_period_contribution', 'contributions', ['user_id', 'period'])
    op.add_column('users', sa.Column('last_seen_month', sa.String(length=7), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen_month')
    op.drop_constraint('uq_user_period_contribution', 'contributions', type_='unique')
    op.drop_column('contributions', 'period')
    # ### end Alembic commands ###
