"""add team crest urls to matches

Revision ID: 7ba5c0412c54
Revises: 646b60410aa5
Create Date: 2026-08-19 02:57:47.865132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ba5c0412c54'
down_revision: Union[str, Sequence[str], None] = '646b60410aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('home_team_crest', sa.String(length=255), nullable=True))
    op.add_column('matches', sa.Column('away_team_crest', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'away_team_crest')
    op.drop_column('matches', 'home_team_crest')
    # ### end Alembic commands ###
