"""add hide_from_leaderboard flag

Revision ID: b496014c8b97
Revises: dea74ace7bf6
Create Date: 2026-08-19 03:24:10.362996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b496014c8b97'
down_revision: Union[str, Sequence[str], None] = 'dea74ace7bf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'hide_from_leaderboard', sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hide_from_leaderboard')
    # ### end Alembic commands ###
