"""add has_seen_rules flag to users

Revision ID: dea74ace7bf6
Revises: 7ba5c0412c54
Create Date: 2026-08-19 03:04:01.052363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dea74ace7bf6'
down_revision: Union[str, Sequence[str], None] = '7ba5c0412c54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('has_seen_rules', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_seen_rules')
    # ### end Alembic commands ###
